library/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView

from .views import *

urlpatterns = patterns('',
    url(r'^$', LoginView.as_view(), name='library_home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login',
        kwargs={'login_url': reverse_lazy('login')}, name='logout'),
    url(r'^registration/$', RegisterView.as_view(), name='registration'),
    url(r'^search/$', SearchView.as_view(), name='library_search'),
    url(r'^add-book/$', AddBookView.as_view(), name='add_book'),
    url(r'^success/$', TemplateView.as_view(template_name='library/success.html'), name='success'),
    url(r'^book/$', BookListView.as_view(), name='book_list'),
    url(r'^book/create/$', BookCreateView.as_view(), name='book_create'),
    url(r'^book/(?P<pk>\d+)/update/$', BookUpdateView.as_view(), name='book_update'),
    url(r'^book/(?P<pk>\d+)/delete/$', BookDeleteView.as_view(), name='book_deete'),

    url(r'^year/$', YearListView.as_view(), name='year_list'),
    url(r'^changes/$', ChangedBookListView.as_view(), name='changed_book_list'),
    url(r'^new/$', NewBookListView.as_view(), name='new_book_list'),

    url(r'^author/$', AuthorListView.as_view(), name='author_list'),

    url(r'^book/(?P<pk>\d+)/$', BookDetailView.as_view(), name='book_detail'),
    url(r'^year/(?P<year>\d{4})/$', YearDetailView.as_view(), name='year_detail'),

    url(r'^author/(?P<pk>\d+)/$', AuthorDetailView.as_view(), name='author_detail'),
   )

library/models.py
from datetime import date
from django.utils.translation import ugettext as _

from django.db import models


class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name=_(u'Created'))
    modified = models.DateTimeField(auto_now=True, verbose_name=_('Modified'))

    class Meta:
        abstract = True


class Author(TimeStampedModel):
    name = models.TextField(unique=True, verbose_name=_(u'Author name'))

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return self.name


class Genre(models.Model):
    genre = models.CharField(max_length=100, verbose_name=_('Genre'))

    def __unicode__(self):
        return self.genre


class Seria(models.Model):
    seria = models.CharField(max_length=50, verbose_name=_(u'Seria'))


    def __unicode__(self):
        return self.seria


class Book(TimeStampedModel):
    origkey = models.CharField(max_length=36, blank=True, null=True, verbose_name=_(u'Original key'))
    title = models.TextField(verbose_name=_(u'Title'))
    file = models.FileField(upload_to='books', verbose_name=_(u'File'))
    sortkey = models.TextField('Authors', blank=True)
    year_published = models.DateField()
    authors = models.ManyToManyField(Author)
            #    default=u'?', on_delete=models.SET_DEFAULT)
    comment = models.TextField(blank=True)
    genre = models.ForeignKey(Genre, blank=True, null=True)
    seria = models.ForeignKey(Seria, blank=True, null=True)

    class Meta:
        ordering = ('sortkey', 'year_published', 'title')

    def __unicode__(self):
        return u'%s (%s): "%s"' % (self.sortkey, self.year_published, self.title) 

    @models.permalink
    def get_absolute_url(self):
        return ('book_detail', (), {'pk': self.pk})

    def display_authors(self):
        if self.sortkey:
            return self.sortkey
        return u', '.join([a.name for a in self.authors.all()])

    def display_year_published(self):
        "We only care about the year"

        return self.year_published.strftime(u'%Y')

    def set_sortkey(self):
        "Generate a sortkey"

        if not self.sortkey and self.authors:
            self.sortkey = ', '.join([a.name for a in self.authors.all()])
            self.save()

    @staticmethod
    def from_dict(book):
        """Add a book from a dict. 

        Format of dict:
            title:      string
            year:       int or None
            authors:    list of strings
            sortkey:    string of authors in the order they appear on
                        the cover
            origkey:    (optional) original key, like an ISBN, or if
                        converting from another system
        """

        # Unknown years is okay
        year = book.get('year', None)
        try:
            int(year)
            year = date(year, 1, 1)
        except TypeError:
            year = None

        # Books can have more than one author, some have none
        author_ids = []
        for a in book.get('authors', []):
            author, created = Author.objects.get_or_create(name=a)
            author_ids.append(author.id)
        authors = Author.objects.filter(id__in=author_ids)

        # Make the book
        book, created = Book.objects.get_or_create(
                title=book['title'],
                year_published=year, 
                origkey=book.get('origkey', None),
                sortkey=book.get('sortkey', u''),
        )

        # Add the authors
        for author in authors:
            book.authors.add(author)

        # Make a sortkey in case it is missing
        book.set_sortkey()

        return book

library/forms.py
from django.forms import ModelForm
from library.models import Book


# Create the form class.
class AddBookForm(ModelForm):

    class Meta:
        model = Book
        fields = [
            'title',
            'year_published',
            'authors',
            'comment',
            'genre',
            'seria',
            'file'
        ]

library/views.py
import operator
import json
from django.contrib.auth.decorators import login_required
from django.core.serializers.json import DjangoJSONEncoder
from django.core import serializers
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.utils.decorators import method_decorator
from django.views.generic import FormView, View
from django.contrib.auth.views import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.views.generic import ListView, DetailView
from django.views.generic import YearArchiveView
from django.views.generic import UpdateView, CreateView, DeleteView
from library.forms import AddBookForm
from library.models import Seria, Genre
from django.db.models import Q

from .models import Book, Author


class RegisterView(FormView):
    template_name = "library/registration.html"
    form_class = UserCreationForm

    def form_valid(self, form):
        form.save()
        user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password1'])
        login(self.request, user)
        return HttpResponseRedirect(reverse_lazy('book_list'))


class AddBookView(FormView):
    template_name = "library/add_book.html"
    form_class = AddBookForm

    def form_valid(self, form):
        if self.request.user.is_authenticated():
            form.save()
            return HttpResponseRedirect(reverse_lazy('success'))
        else:
            return HttpResponseRedirect(reverse_lazy('login'))


class LoginView(FormView):
    template_name = "library/login.html"
    form_class = AuthenticationForm

    def form_valid(self, form):
        user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password'])
        login(self.request, user)
        return HttpResponseRedirect(reverse_lazy('book_list'))


class SearchView(ListView):
    http_method_names = ('get',)
    template_name = 'library/search_results.html'
    model = Book

    def get_queryset(self):
        query = self.request.GET.get('q', u'').split()
        self.query = u' '.join(query)
        qs = self.model._default_manager
        if not query:
            return qs.none()
        q_objects = []
        for term in query:
            q_objects.append(Q(title__icontains=term))
            q_objects.append(Q(sortkey__icontains=term))


        q_objects = reduce(operator.or_, q_objects)
        return qs.select_related('location').filter(q_objects)

    def render_to_response(self, context, **response_kwargs):
        context['query'] = self.query
        return self.response_class(
                request = self.request,
                template = self.get_template_names(),
                context = context,
                **response_kwargs
        )

class BookListView(ListView):
    model = Book

    @method_decorator(login_required(login_url=reverse_lazy('login')))
    def dispatch(self, *args, **kwargs):
        return super(BookListView, self).dispatch(*args, **kwargs)


class YearListView(ListView):
    queryset = Book.objects.order_by('year_published')

class ChangedBookListView(ListView):
    queryset = Book.objects.order_by('-modified')[:10]
    template_name = 'library/book_list_with_dates.html'

class NewBookListView(ListView):
    queryset = Book.objects.order_by('-created')[:10]
    template_name = 'library/book_list_with_dates.html'

class YearDetailView(YearArchiveView):
    queryset = Book.objects.all()
    allow_empty = True 
    allow_future = True
    date_field = 'year_published'
    make_object_list = True

class BookDetailView(DetailView):
    model = Book

class BookUpdateView(UpdateView):
    model = Book

class BookDeleteView(DeleteView):
    model = Book
    success_url = reverse_lazy('book_list')

class BookCreateView(CreateView):
    model = Book

class AuthorListView(ListView):
    model = Author

class AuthorDetailView(DetailView):
    model = Author



class AutoCompleteView(View):
    def get(self, *args, **kwargs):
        books = []
        for i in serializers.serialize('python', Book.objects.filter(title__startswith=self.request.GET.get('term', '')), fields=("title", )):
            books.append(i['fields']['title'])
        return HttpResponse(json.dumps(books))

library/templates/library/_search_form.html
{% load i18n %}
<form method="get" action="{% url 'library_search' %}">
<span>{% trans 'Search' %}</span>
<input id="search_id" type="text" name="q">
</form>
<script>
    $( "#search_id" ).autocomplete({
      source: "http://localhost:8000/autocomplete/",
      minLength: 2,
    });
</script>

library/templates/library/add_book.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <form enctype="multipart/form-data" action="{% url 'add_book' %}" method="post">
    {{form.non_field_errors}}
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit"  >{% trans 'Add' %}</button>
    </form>
{% endblock content%}

{% block side-menu %}
{% endblock side-menu %}

library/templates/library/author_detail.html
{% extends "library/base.html" %}
{% load url from future %}

{% block content %}

<h2>{{ object.name }}</h2>
<p>{% for book in object.book_set.all %}
<a href="{% url 'book_detail' pk=book.pk %}">{{ book.title }}</a>
</p>
<p>{{ book.year_published|date:"Y" }}</p>

{% endfor %}
{% endblock content %}

library/templates/library/author_list.html
{% extends "library/base.html" %}
{% load url from future %}

{% block content %}
<table class="table">
{% for author in object_list %}
<tr>
<td><a href="{% url 'author_detail' pk=author.pk %}">{{ author.name }}</a></td>
</tr>
{% endfor %}
</table>
{% endblock content %}

library/templates/library/base.html
{% extends "base.html" %}

{% block header %}
{% include "library/_search_form.html" %}
{% endblock header %}

library/templates/library/book_archive_year.html
{% extends "library/base.html" %}
{% load url from future %}

{% block content %}
<h2>Books published in {{ year }}</h2>
<table>
{% for book in object_list %}
<tr>
<td><a href="{% url 'book_detail' pk=book.pk %}">{{ book.title }}</a></td>
<td>{{ book.sortkey }}</td>

</tr>
{% endfor %}
</table>
<p>
<a href="{{ previous_year }}">{{ previous_year }}</a>
<a href="{{ next_year }}">{{ next_year }}</a>
</p>
{% endblock content %}

library/templates/library/book_detail.html
{% extends "library/base.html" %}
{% load url from future %}

{% block content %}

<h2>{{ object.title }}</h2>
<p>{% for author in object.authors.all %}
<a href="{% url 'author_detail' pk=author.pk %}">{{ author.name }}</a>
{% endfor %}
</p>
<p>{{ object.year_published|date:"Y" }}</p>

{% endblock content %}

library/templates/library/book_form.html
{% extends "library/base.html" %}
{% load url from future %}

{% block content %}

<h2>{{ object.title }}</h2>
<form action="." method="post">
<table>
 {% csrf_token %}
{{ form }}
<tr><th></th><td><input type="submit" /></td></tr>
</table>
</form>
{% endblock content %}

library/templates/library/book_list_with_dates.html
{% extends "library/base.html" %}
{% load url from future %}

{% block content %}
<table>
{% for book in object_list %}
<tr>
<td style="width: 20ex">{{ book.modified|date:"Y-m-d H:i:s" }}</td>
<td><a href="{% url 'book_detail' pk=book.pk %}">{{ book.title }}</a></td>
<td>{{ book.sortkey }}</td>
<td><a href="{% url 'year_detail' year=book.year_published %}">{{ book.year_published|date:"Y" }}</a></td>

</tr>
{% endfor %}
</table>
{% endblock content %}

library/templates/library/location_detail.html
{% extends "library/base.html" %}
{% load url from future %}

{% block content %}

<h2>{{ object.name }}</h2>
<p>{% for book in object.book_set.all %}
<a href="{% url 'book_detail' pk=book.pk %}">{{ book.title }}</a>
</p>
<p>{{ book.sortkey }}</p>
<p>{{ book.year_published|date:"Y" }}</p>
{% endfor %}
{% endblock content %}

library/templates/library/login.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <form action="{% url 'login' %}" method="post">
    {{form.non_field_errors}}
    {%csrf_token%}
    {{form.as_p}}
    <button class="btn btn-success" type="submit"  >{% trans 'Sign in' %}</button>
    <a href="{% url 'registration' %}">
        <span>or</span>
    <button class="btn btn-primary" type="button"  >{% trans 'Register' %}</button>
    </a>
    </form>

{% endblock content%}

{% block side-menu %}
{% endblock side-menu %}

library/templates/library/registration.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <form action="{% url 'registration' %}" method="post">
    {{form.non_field_errors}}
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit"  >{% trans 'Register' %}</button>
    </form>
{% endblock content%}

{% block side-menu %}
{% endblock side-menu %}

library/templates/library/search_results.html
{% extends "library/base.html" %}
{% load i18n %}
{% load url from future %}

{% block content %}
<h2>{% blocktrans %}Your search for "{{ query }}" returned {{ object_list.count }} results{% endblocktrans %}</h2>
<table class="table">
{% for book in object_list %}
<tr>
<td><a href="{% url 'book_detail' pk=book.pk %}">{{ book.title }}</a></td>
<td>{{ book.sortkey }}</td>
<td><a href="{% url 'year_detail' year=book.year_published|date:'Y' %}">{{ book.year_published|date:"Y" }}</a></td>

</tr>
{% endfor %}
</table>
{% endblock content %}

library/templates/library/success.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block content %}
<h2>{% blocktrans %}Your book added successfully{% endblocktrans %}</h2>
<a href="{% url 'book_list' %}">
    <button type="button"  >{% trans 'Home' %}</button>
</a>
{% endblock content %}